<?php

namespace AppBundle\Repository;

/**
 * CuartoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CuartoRepository extends \Doctrine\ORM\EntityRepository
{
}
