<?php

namespace AppBundle\Repository;

/**
 * ReservacionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservacionRepository extends \Doctrine\ORM\EntityRepository
{
	public function buscarFecha($mes,$año){
		$em = $this->getEntityManager(); 
		$qb = $em->createQueryBuilder();
		$qb->select('r')
		->from('AppBundle:Reservacion', 'r')
		->where('MONTH(r.fechaInicio) = :mes AND YEAR(r.fechaInicio) = :anio')
		->andWhere('MONTH(r.fechaFin) = :mes AND YEAR(r.fechaFin) = :anio')
		->setParameter('mes',$mes)
		->setParameter('anio',$año);
		$query = $qb->getQuery();
		return $query->getResult();
	}
}
