<?php

namespace AppBundle\Repository;

/**
 * ReservaPersonaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservaPersonaRepository extends \Doctrine\ORM\EntityRepository
{
}
