<?php

namespace AppBundle\Repository;

/**
 * ServiciosUsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiciosUsRepository extends \Doctrine\ORM\EntityRepository
{
}
