app:
    resource: '@AppBundle/Controller/'
    type: annotation

logout:
    path: /logout

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }